### ISSUE TITLE
Don't allow to click outside modal to close it

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#310] opened 2021-03-16 18:17 UTC
We should use a button to close the modal and disable the ability to close it clicking outside since is very easy to click outside and lost the data entered on a form

**Comment by willjgriff** [comment] 2021-03-18 10:21
I don't think clicking outside the modal is a problem. I think the issue is that if you click inside the modal, then release the click outside it then it closes. That shouldn't happen, but I think clicking and releasing outside the modal should close it.

**Comment by fabriziovigevani** [comment] 2021-03-22 21:00
closed by https://github.com/1Hive/1hive-ui/pull/7

**Closed by fabriziovigevani** 2021-03-22 21:00 UTC
